---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: docker-publish
  image: plugins/docker
  settings:
    context: "."
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/rdns-server
    tag: "${DRONE_TAG}-rancher-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: fossa

steps:
- name: fossa
  image: rancher/drone-fossa:latest
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    when:
      instance:
        - drone-publish.rancher.io
